# Generated by Django 3.1.7 on 2021-03-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_forsellernotification_selleraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForAllSellersNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
