# Generated by Django 3.1.7 on 2021-04-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20210410_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
