# Generated by Django 3.1.7 on 2021-04-08 03:11

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourist', '0001_initial'),
        ('tours', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_confirmation', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('qr_code', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='qr-codes/')),
                ('paid_out', models.BooleanField(default=False)),
                ('tour_date', models.CharField(blank=True, max_length=100, null=True)),
                ('tour_time', models.CharField(blank=True, max_length=20, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_purchases', to='tours.offer')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_purchases', to='seller.seller')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_purchases', to='tours.tour')),
                ('tour_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='tours.offerlanguage')),
                ('tourist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_purchases', to='tourist.tourist')),
            ],
            options={
                'ordering': ('-purchase_date',),
            },
        ),
    ]
