# Generated by Django 3.1.7 on 2021-03-10 09:03

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourist', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_confirmation', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('qr_code', easy_thumbnails.fields.ThumbnailerImageField(upload_to='qr-codes/')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_purchases', to='tours.offer')),
                ('tourist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_purchases', to='tourist.tourist')),
            ],
            options={
                'ordering': ('-purchase_date',),
            },
        ),
    ]
