# Generated by Django 3.1.7 on 2021-03-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_auto_20210315_1719'),
        ('seller', '0003_forallsellersnotification'),
        ('orders', '0002_auto_20210313_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpurchase',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_purchases', to='seller.seller'),
        ),
        migrations.AddField(
            model_name='tourpurchase',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='tour_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='tours.offerlanguage'),
        ),
    ]
