# Generated by Django 3.1.7 on 2021-03-15 11:23

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_auto_20210315_1719'),
        ('orders', '0003_auto_20210315_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpurchase',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_purchases', to='tours.tour'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='qr_code',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='qr-codes/'),
        ),
    ]
