# Generated by Django 3.1.7 on 2021-03-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210315_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpurchase',
            name='paid_out',
            field=models.BooleanField(default=False),
        ),
    ]
