# Generated by Django 3.1.7 on 2021-03-14 13:33

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='sellers/')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
