# Generated by Django 3.1.7 on 2021-03-15 06:35

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslide',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='home_slides/'),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
