# Generated by Django 3.1.7 on 2021-04-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210414_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
