# Generated by Django 3.1.7 on 2021-03-10 09:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Category title')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='categories/')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='tours/')),
                ('duration', models.CharField(max_length=50)),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('important_information', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('not_suitable_for', models.TextField(help_text='the list must be separated by commas', null=True)),
                ('will_need', models.TextField(help_text='the list must be separated by commas', null=True)),
                ('prohibited', models.TextField(help_text='the list must be separated by commas', null=True)),
                ('views', models.IntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='tours', to='tours.Category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tours.city')),
            ],
            options={
                'ordering': ('publication_date',),
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='tours/')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='tours.tour')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('included', models.TextField(help_text='the list must be separated by commas')),
                ('excluded', models.TextField(help_text='the list must be separated by commas')),
                ('transfer', models.BooleanField(default=False)),
                ('transfer_detail', models.TextField(null=True)),
                ('languages', models.TextField(help_text='the list must be separated by commas')),
                ('active', models.BooleanField(default=False)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='seller.seller')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='tours.tour')),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='tours.country'),
        ),
    ]
