# Generated by Django 3.1.7 on 2021-03-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ('-publication_date',)},
        ),
        migrations.AddField(
            model_name='offer',
            name='age_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='times',
            field=models.CharField(blank=True, help_text='the list must be separated by commas', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
