# Generated by Django 3.1.7 on 2021-04-10 12:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('order', 'title'), 'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='tour',
            name='future',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='important_information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='not_suitable_for',
            field=models.TextField(blank=True, help_text='the list must be separated by commas', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='prohibited',
            field=models.TextField(blank=True, help_text='the list must be separated by commas', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='will_need',
            field=models.TextField(blank=True, help_text='the list must be separated by commas', null=True),
        ),
    ]
