# Generated by Django 3.1.7 on 2021-04-14 02:14

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20210410_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='full_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='cities/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='cities/'),
        ),
    ]
