# Generated by Django 3.1.7 on 2021-03-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20210313_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Duration (hours)'),
        ),
    ]
