# Generated by Django 3.1.7 on 2021-03-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20210313_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='offer',
            name='languages',
        ),
        migrations.AddField(
            model_name='offer',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='tours.OfferLanguage'),
        ),
    ]
