# Generated by Django 3.1.7 on 2021-04-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20210414_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ('-publication_date', 'order')},
        ),
        migrations.AddField(
            model_name='tour',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
