# Generated by Django 3.1.7 on 2021-04-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20210414_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
