# Generated by Django 3.1.7 on 2021-03-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20210314_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='age_restrictions',
        ),
        migrations.AddField(
            model_name='offer',
            name='max_age',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_age',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='offer',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='offers', to='tours.OfferLanguage'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price USD'),
        ),
    ]
