# Generated by Django 3.1.7 on 2021-04-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
