# Generated by Django 3.1.7 on 2021-03-14 06:41

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20210314_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('-register_date',)},
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
