# Generated by Django 3.1.7 on 2021-04-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_offer_review_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='review_count',
            new_name='reviews_count',
        ),
    ]
