# Generated by Django 3.1.7 on 2021-03-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20210314_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('order',), 'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
