# Generated by Django 3.1.7 on 2021-03-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20210314_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='times',
        ),
        migrations.AddField(
            model_name='offer',
            name='times',
            field=models.ManyToManyField(blank=True, related_name='offers', to='tours.OfferTime'),
        ),
    ]
