# Generated by Django 3.1.7 on 2021-03-15 06:42

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20210315_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offertime',
            options={'ordering': ('time',)},
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='tours/')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='tours.offer')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
