# Generated by Django 3.1.7 on 2021-03-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_auto_20210315_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='offerimage',
            name='order',
        ),
    ]
