# Generated by Django 3.1.7 on 2021-04-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_auto_20210417_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='offertime',
            options={},
        ),
        migrations.AddField(
            model_name='offer',
            name='everyday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offertime',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='offers', to='tours.OfferDate'),
        ),
    ]
