# Generated by Django 3.1.7 on 2021-03-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_offer_children_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='children_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Children price USD'),
        ),
    ]
