# Generated by Django 3.1.7 on 2021-04-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_auto_20210417_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='duration',
        ),
        migrations.AddField(
            model_name='offer',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Duration (hours)'),
        ),
    ]
