# Generated by Django 3.1.7 on 2021-03-10 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('whatsapp', models.CharField(max_length=25)),
                ('avatar', easy_thumbnails.fields.ThumbnailerImageField(upload_to='tourists_avatars/')),
                ('active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tourist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-register_date',),
            },
        ),
    ]
