# Generated by Django 3.1.7 on 2021-03-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0002_reviewphoto_tourreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
