# Generated by Django 3.1.7 on 2021-03-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0003_auto_20210313_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourreview',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
